import { StyleSheet } from "react-native";

export const Styles = StyleSheet.create({
  container: {
    width: "100%",
    height: "100%",
    backgroundColor: "#FFF",
    position: "absolute",
    flex: 1,
  },
  content: {
    flex: 1,
    padding: 40,
    paddingTop: 0,
    paddingBottom: 60
  },
  name: {
    fontSize: 30,
    fontWeight: "bold",
    marginTop: -12
  },
  mailContainer: {
    flex: 1,
    paddingLeft: 65,
    fontSize: 17,
    height: 54,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginBottom: 23,
  },
  inputContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 29,
  },
  input: {
    flex: 1,
    paddingLeft: 65,
    borderWidth: 1,
    borderColor: "#B0B0B0",
    fontSize: 17,
    borderRadius: 7,
    height: 54,
  },
  inputFocused: {
    flex: 1,
    paddingLeft: 65,
    borderWidth: 1,
    borderColor: "#FF9900",
    fontSize: 17,
    borderRadius: 7,
    height: 54,
  },
  image_logo: {
    width: "110%",
    height: 250,
    resizeMode: "contain",
    marginBottom: 24,
  },
  verticalLine: {
    height: 30,
    width: 1.5,
    backgroundColor: "#B0B0B0",
    position: "absolute",
    left: 50,
    zIndex: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  horizontalLine: {
    width: "100%",
    borderBottomColor: "#FF9900",
    borderBottomWidth: 2.5,
    marginTop: 18,
    marginBottom: 16,
    // shadowColor: "#000",
    // shadowOffset: {
    //   width: 0,
    //   height: 1,
    // },
    // shadowOpacity: 0.22,
    // shadowRadius: 2.22,
  },
  iconRight: {
    position: "absolute",
    right: 13,
    zIndex: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  iconLeft: {
    position: "absolute",
    left: 9,
    zIndex: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  phone: {
    position: "absolute",
    left: 14,
    zIndex: 100,
    justifyContent: "center",
    alignItems: "center",
  },
});
