import { StyleSheet } from "react-native";

export const Styles = StyleSheet.create({
    container: {
      width: "100%",
      height: "100%",
      backgroundColor: "#FFF",
      position: "absolute",
      flex: 1,
    },
    content: {
      flex: 1,
      padding: 50,
      paddingTop: 12,
    },
    field: {
      marginBottom: 19,
    },
    titulo: {
      fontSize: 20,
      marginBottom: 4,
    },
    inputTitle: {
      borderBottomWidth: 1,
      borderBottomColor: "#B0B0B0",
      marginTop: 2,
      fontSize: 17,
    },
    inputTitleFocused: {
      borderBottomWidth: 1,
      borderBottomColor: "#FF9900",
      marginTop: 2,
      fontSize: 17,
    },
    row: {
      flexDirection: "row",
    },
    inputMeta: {
      borderWidth: 1,
      borderColor: "#B0B0B0",
      borderRadius: 4,
      height: 24,
      width: 64,
      marginRight: 10,
      paddingHorizontal: 5,
      fontSize: 16,
    },
    inputMetaFocused: {
      borderWidth: 1,
      borderColor: "#FF9900",
      borderRadius: 4,
      height: 24,
      width: 64,
      marginRight: 10,
      paddingHorizontal: 5,
      fontSize: 16,
    },
    subtitle: {
      fontSize: 17,
      fontWeight: "thin",
      color: "#888",
      marginRight: 22,
    },
    inputLocContainer: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
    },
    inputLoc: {
      flex: 1,
      paddingLeft: 33,
      borderWidth: 1,
      borderColor: "#B0B0B0",
      marginTop: 2,
      fontSize: 17,
      borderRadius: 4,
      height: 34,
      marginLeft: -25,
    },
    inputLocFocused: {
      flex: 1,
      paddingLeft: 33,
      borderWidth: 1,
      borderColor: "#FF9900",
      marginTop: 2,
      fontSize: 17,
      borderRadius: 4,
      height: 34,
      marginLeft: -25,
    },
    inputDesc: {
      borderWidth: 1,
      borderColor: "#B0B0B0",
      marginTop: 2,
      fontSize: 17,
      borderRadius: 4,
      height: 90,
      padding: 7,
    },
    inputDescFocused: {
      borderWidth: 1,
      borderColor: "#FF9900",
      marginTop: 2,
      fontSize: 17,
      borderRadius: 4,
      height: 90,
      padding: 7,
    },
  });